### "Sort" function

In [1]:
import numpy as np

In [2]:
from pylab import *

In [3]:
a=np.array([0,-5,1,4,-3,6,8,15,2])
a

array([ 0, -5,  1,  4, -3,  6,  8, 15,  2])

In [4]:
a.sort()
a

array([-5, -3,  0,  1,  2,  4,  6,  8, 15])

In [5]:
np.sort(a)

array([-5, -3,  0,  1,  2,  4,  6,  8, 15])

### What about descending sort?

In [6]:
a=np.array([0,-5,1,4,-3,6,8,15,2])
a.sort()
a[::-1]
print("Dfault sort=",a)
print("Descending sort of a=",a[::-1])

Dfault sort= [-5 -3  0  1  2  4  6  8 15]
Descending sort of a= [15  8  6  4  2  1  0 -3 -5]


### What about descending sort for a list?

In [7]:
b=[0,-5,1,4,-3,6,8,15,2]
b.sort(reverse = True)
print(b)

[15, 8, 6, 4, 2, 1, 0, -3, -5]


## Sorting using "for" loop

In [8]:
b=[0,-5,1,4,-3,6,8,15,2] # Ascending order
for i in range(len(b)-1):
        for j in range(i+1,len(b)):
            if b[j]<b[i]:
                t=b[i]
                b[i]=b[j]
                b[j]=t    
b    

[-5, -3, 0, 1, 2, 4, 6, 8, 15]

In [9]:
b=[0,-5,1,4,-3,6,8,15,2] # Descending order
for i in range(len(b)-1):
    
    for j in range(i+1,len(b)):
            if b[j]>b[i]:
                t=b[i]
                b[i]=b[j]
                b[j]=t
b    

[15, 8, 6, 4, 2, 1, 0, -3, -5]