# NumPy Quick Start (Part 1 of 2)

### The Basics

- NumPy is a Python library that provides fast operations on multi-dimensional arrays.
- [NumPy and MATLAB have a lot in common, but they also have many differences](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html).
- An ndarray object is a homogeneous (the elements are all of the same type) multi-dimensional array.
- NymPy array operations are much faster than Python `for` and `while` loops. Watch [this YouTube video](https://www.youtube.com/watch?v=EEUXKG97YRw).
- https://chatgpt.com/share/66f97185-ae9c-8000-bc80-91c468859e9e

In [1]:
import numpy as np

In [5]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
y=np.array([10,20,30])
y

array([10, 20, 30])

In [9]:
x+y

array([11, 22, 33])

In [11]:
a=[1,2,3]
b=[10,20,30]
a+b

[1, 2, 3, 10, 20, 30]

### Array Creation

In [4]:
a = np.array([0, 1, 2, 3])  # 1D array from a list
a

array([0, 1, 2, 3])

In [6]:
 b= np.array([1,2,3,4])

In [8]:
a+b

array([1, 3, 5, 7])

In [10]:
x=[0, 1, 2, 3]
y=[1,2,3,4]
x+y

[0, 1, 2, 3, 1, 2, 3, 4]

In [13]:
c=np.array([1,2,"3",4])
c

array(['1', '2', '3', '4'], dtype='<U21')

In [15]:
type(c)

numpy.ndarray

In [ ]:
x=[0, 1, 2, 3] # list
y=[1,2,3,4] # list

In [ ]:
x+y # list concatination

In [17]:
a = np.array((0, 1, 2, 3))  # 1D array from a tuple
a                           # np.array(0, 1, 2, 3) does not work

array([0, 1, 2, 3])

In [19]:
b = np.array([[0, 1], [2, 3]])  # 2D array from a list of lists
b

array([[0, 1],
       [2, 3]])

In [21]:
c = np.array([3, '4.5'])  # Homogeneous data type
c

array(['3', '4.5'], dtype='<U21')

In [23]:
np.array([3, '4.5', [1, -2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

- `np.array([3, '4.5', [1, -2]])` will produce an error. We can modify it in the following two ways:

In [25]:
c = np.array([3, '4.5', 1, -2])
c

array(['3', '4.5', '1', '-2'], dtype='<U21')

In [27]:
c = np.array([[3, '4.5'], [1, -2]])
c

array([['3', '4.5'],
       ['1', '-2']], dtype='<U21')

In [35]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [29]:
c = np.arange(1,10,2)  # Returns an array instead of a list
c

array([1, 3, 5, 7, 9])

In [37]:
np.arange(-2, 1, 0.5)  # Interval is 0.5

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5])

- `range(-2, 1, 0.5)` does not work.

In [41]:
np.linspace(0, 2, 4)  # 4 elements equally distributed
                      # between 0 and 2 (inclusive)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [43]:
np.linspace(1,5,5) # linspace(a,b,n)

array([1., 2., 3., 4., 5.])

##### Equivalent function to np.linspace(a,b,n)?

In [42]:
def f(a, b, n):
    if n == 1:
        return [a]  # Return only the start value if n == 1
    
    step = (b - a) / (n - 1)  # Calculate the step size
    return [a + i * step for i in range(n)]

f(1,5,5)


[1.0, 2.0, 3.0, 4.0, 5.0]

In [45]:
np.ones([2, 3])  # Array of ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.zeros([2, 3])  # Array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((2, 3))  # np.zeros(2, 3) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
u = np.eye(3)  # 2D unit array
u

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
a = np.array([1, 2, 3])
d = np.diag(a)  # 2D diagonal array
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Array Attributes

In [61]:
d.ndim  # Number of dimensions 

2

In [63]:
d.shape # Length of each dimension

(3, 3)

In [65]:
d.size  # Total number of elements

9

### Array Reshaping

In [69]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [71]:
c.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
c  # Reshaping is not done in-place

array([0, 1, 2, 3, 4, 5])

In [75]:
c = c.reshape(2, 3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
c.reshape((3, -1))  # -1 means unspecified

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
c.ravel()  # Flattening

array([0, 1, 2, 3, 4, 5])

In [ ]:
c  # Flattening is not done in-place

### Element-Wise Arithmetic Operations

In [83]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [85]:
b = np.arange(2, 6)
b

array([2, 3, 4, 5])

In [87]:
c = a + b
c

array([22, 33, 44, 55])

In [89]:
c = a - b
c

array([18, 27, 36, 45])

In [91]:
c = a * b
c

array([ 40,  90, 160, 250])

In [93]:
c = a / b
c

array([10., 10., 10., 10.])

In [95]:
b

array([2, 3, 4, 5])

In [97]:
b ** 2

array([ 4,  9, 16, 25])

In [99]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [101]:
np.exp(b) #Euler exponential

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ])

In [103]:
np.sqrt(a)

array([4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [98]:
a

array([20, 30, 40, 50])

In [105]:
a <= 35

array([ True,  True, False, False])

### Compare with Lists

In [ ]:
a = [20, 30, 40, 50]
a

In [ ]:
b = list(range(2, 6))
b

In [ ]:
a + b  # List concatination

In [ ]:
a-b

- `a - b` does not work. It's not defined for lists.

In [ ]:
a * 2  # List repetition

- `a / b` does not work. It's not defined for lists.

### Multiplication

In [107]:
A = np.array([[1,1], [0,1]]) 
A

array([[1, 1],
       [0, 1]])

In [109]:
B = np.array([[2,0], [3,4]])
B

array([[2, 0],
       [3, 4]])

In [111]:
A * B           # Elementwise product

array([[2, 0],
       [0, 4]])

In [113]:
np.dot(A, B)    # Matrix product

array([[5, 4],
       [3, 4]])

def linespace(a,b,n):
    c=a
    x=[c]
    step=(b-a)/(n-1)
    for i in range(1,n):
        c=c+step
        x.append(c)

    return x

### In-class Exercises: https://chatgpt.com/share/66f97055-2dc8-8000-9a28-cbd23be17a8d
