# NumPy Quick Start (Part 2 of 2)

### Statistics

In [3]:
import numpy as np

In [5]:
a = np.array([[0,1], [2,3]])
a

array([[0, 1],
       [2, 3]])

In [9]:
print(np.sum(a))

6


In [11]:
np.sum(a, axis=0)  # Sum of each column

array([2, 4])

In [13]:
np.sum(a, axis=1)  # Sum of each row

array([1, 5])

In [15]:
a

array([[0, 1],
       [2, 3]])

In [17]:
print(np.min(a))

0


In [19]:
print(np.max(a))

3


In [21]:
print(np.mean(a))

1.5


In [23]:
a

array([[0, 1],
       [2, 3]])

In [25]:
print(np.median(a))

1.5


In [27]:
print(np.var(a))

1.25


In [29]:
print(np.std(a))

1.118033988749895


In [31]:
numbers=np.arange(1,1000,3)
numbers

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154,
       157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193,
       196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232,
       235, 238, 241, 244, 247, 250, 253, 256, 259, 262, 265, 268, 271,
       274, 277, 280, 283, 286, 289, 292, 295, 298, 301, 304, 307, 310,
       313, 316, 319, 322, 325, 328, 331, 334, 337, 340, 343, 346, 349,
       352, 355, 358, 361, 364, 367, 370, 373, 376, 379, 382, 385, 388,
       391, 394, 397, 400, 403, 406, 409, 412, 415, 418, 421, 424, 427,
       430, 433, 436, 439, 442, 445, 448, 451, 454, 457, 460, 463, 466,
       469, 472, 475, 478, 481, 484, 487, 490, 493, 496, 499, 502, 505,
       508, 511, 514, 517, 520, 523, 526, 529, 532, 535, 538, 54

In [33]:
print(np.median(numbers))

499.0


In [35]:
np.var(numbers)

83166.0

In [37]:
np.mean(numbers)

499.0

In [39]:
np.std(numbers)

288.3851591188423

In [41]:
numbers[-1] # The last element of the array. 

997

### Linear Algebra Operations

In [43]:
a

array([[0, 1],
       [2, 3]])

In [45]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [47]:
a.T # alternative way of transpose

array([[0, 2],
       [1, 3]])

In [49]:
a

array([[0, 1],
       [2, 3]])

In [51]:
np.linalg.inv(a)  # The inverse matrix

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [53]:
b = np.array([[5], [7]])
b

array([[5],
       [7]])

- Solve $\textbf{ax = b} \Rightarrow 
\begin{bmatrix} 
0 & 1 \\
2 & 3 
\end{bmatrix}
\begin{bmatrix} 
x_1 \\
x_2 
\end{bmatrix}
=
\begin{bmatrix} 
5 \\
7 
\end{bmatrix}
$ for **x**.

In [55]:
np.linalg.solve(a, b)  # Solve ax = b for x

array([[-4.],
       [ 5.]])

#### Class exercise
- The total expenses in Jan and Feb of company X is `$60,000`
- if Feb expenses were half of Jan expenses, what was the expenses in each month? 

In [ ]:
# let's assume that x is the total expenses in Jan
# let's assume that y is the total expenses in Feb
x+y=60000 # eq 1
y=(1/2)*x---> 2y=x----> x-2y=0 # eq 2

In [57]:
a=np.array([[1,1],[1,-2]])
b=np.array([[60000],[0]])
np.linalg.solve(a, b)  # Solve ax = b for x

array([[40000.],
       [20000.]])

In [ ]:
# Solution
# assume x is the expenses in Jan and y is the expenses in Feb
# equation 1: 
x+y=60000 #(1)
# equation 2:
y=(1/2)*x
2y=x
x-2y=0 #(2)
# solution


In [ ]:
a=np.array([[1,1],[1,-2]])
b=np.array([[60000],[0]])
np.linalg.solve(a, b)  # Solve ax = b for x

- Find the determinant $
\begin{vmatrix} 
0 & 1 \\
2 & 3 
\end{vmatrix}
$.

In [59]:
a = np.array([[0,1], [2,3]])

np.linalg.det(a)

-2.0

In [61]:
a

array([[0, 1],
       [2, 3]])

In [63]:
np.diag(a)  # Find the diagonal elements

array([0, 3])

In [65]:
np.trace(a)  # Sum of the diagonal elements

3

- Other commonly used LA functions:
    - eig: Compute the eigenvalues and eigenvectors of a square matrix
    - pinv: Compute the Moore-Penrose pseudo-inverse of a matrix
    - qr: Compute the QR decomposition
    - svd: Compute the singular value decomposition (SVD)
    - lstsq: Compute the least-squares solution to Ax = b

### Random Number Generators

In [67]:
samples = np.random.normal(85, 10, size=(4, 4))
samples

array([[69.82232749, 72.58986942, 90.58182363, 88.53102298],
       [70.45678879, 89.20673139, 84.1444901 , 83.63806671],
       [79.45484225, 78.31296324, 76.37946138, 97.70352972],
       [84.7343776 , 88.55767946, 77.371793  , 87.34207394]])

In [69]:
samples = np.random.randn(4, 4)
samples

array([[-2.19759969, -0.08302646,  1.16852697, -0.17839307],
       [ 1.89678222,  1.40216101,  1.92235522, -0.22770483],
       [-0.82614282, -1.15536855, -0.84705642, -0.69834648],
       [ 0.03673525,  0.6702489 ,  0.38381556, -1.10652596]])

In [71]:
samples = np.random.randn(100, 100)
samples

array([[-0.70263719, -1.44484691, -0.69995592, ..., -1.01862164,
         1.33231189,  0.09724068],
       [ 1.23962395, -1.16921059,  0.04302268, ..., -0.00841773,
         1.57578976,  0.3138681 ],
       [-1.02640989,  1.40770936, -1.02537824, ..., -1.01893892,
        -1.15107158,  1.03468159],
       ...,
       [-1.38236373, -0.55906179,  0.41135194, ...,  0.67130896,
         0.02939157, -0.50112122],
       [-0.38783239,  1.0366322 ,  1.36103134, ..., -0.83817621,
         0.7123603 ,  0.48626845],
       [ 0.83063648,  0.76222386, -0.30717208, ..., -0.15333923,
         0.33297274, -0.48259367]])

In [73]:
samples.mean()

-0.025924298061379147

In [75]:
samples.std()

0.9946943284570396

In [79]:
np.random.randint (10,size= (3,3)) 

array([[5, 0, 5],
       [7, 6, 2],
       [6, 7, 3]])

In [81]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [83]:
np.random.permutation(a)

array([3, 4, 0, 2, 1])

In [85]:
np.random.permutation(10)

array([4, 8, 9, 0, 1, 2, 7, 3, 6, 5])

In [87]:
np.random.permutation(a)

array([1, 3, 4, 0, 2])

In [89]:

a

[0, 1, 2, 3, 4]

In [93]:
np.random.shuffle(a)  # Randomly permute a sequence in place

In [95]:
a

[1, 4, 3, 2, 0]

- Other commonly used random number functions:
    - seed: Seed the random number generator
    - uniform: Draw samples from a uniform [low, high) distribution
    - randint: Draw random integers from a discrete uniform [low, high) distribution
    - binomial: Draw samples from a binomial distribution
    - beta: Draw samples from a beta distribution
    - chisquare: Draw samples from a chi-square distribution
    - gamma: Draw samples from a gamma distribution

### Logic Operations

In [97]:
a = [True, True, False]
a

[True, True, False]

In [99]:
np.all(a)  # All true?

False

In [101]:
np.any(a)  # Any true?

True

In [103]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
a == 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [107]:
np.all(a == 0)

True

In [109]:
a != 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [111]:
np.any(a != 0)

False

### Sorting

In [113]:
a = np.random.randn(5)
a

array([ 0.19893435, -0.94778615,  0.24118181, -2.07975377,  0.60113241])

In [115]:
a.sort()  # Sorting is done in-place
a

array([-2.07975377, -0.94778615,  0.19893435,  0.24118181,  0.60113241])

In [117]:
x=[1, 5, 3, 6, -1]
x

[1, 5, 3, 6, -1]

In [119]:
x.sort()
x

[-1, 1, 3, 5, 6]

In [121]:
x

[-1, 1, 3, 5, 6]

In [ ]:
b = np.random.randn(3, 3)
b

In [123]:
b.sort(axis=1)  # Along each row (default)
b

array([[60000],
       [    0]])

In [125]:
b.sort(axis=0)  # Then along each column
b

array([[    0],
       [60000]])

### Row and Column Vectors

- NumPy does not differentiate between 1D row and 1D column vectors.

In [127]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [129]:
b = a.transpose()
b

array([1, 2, 3])

- A column vector can only be represented by a 2D array.

In [131]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [133]:
b.transpose()  # Transposing is not done in-place

array([[1, 2, 3]])

In [ ]:
b

- We can also use `reshape` to make a 2D column array.

In [135]:
np.array([1, 2, 3]).reshape(3, 1)

array([[1],
       [2],
       [3]])

- `r_` and `c_` create arrays by stacking numbers along one axis.

In [137]:
a = np.r_[-2, -1, 1:4]  # Skip over 0
a

array([-2, -1,  1,  2,  3])

In [139]:
np.c_[a]

array([[-2],
       [-1],
       [ 1],
       [ 2],
       [ 3]])

a=np.array([[1,1],[1,-2]])
b=np.array([[60000],[0]])
np.linalg.solve(a, b)

### Class Exercises: https://chatgpt.com/share/66f977cb-81d0-8000-ad0c-6a411f36e7f3

### Example 1: Cost Allocation Problem
Problem Statement: A company produces three products: A, B, and C. The cost of producing these products is represented by the following system of equations:

In [141]:
import numpy as np

# Coefficient matrix (A)
A = np.array([[2, 3, 1],
              [1, 2, 3],
              [3, 1, 2]])

# Constant matrix (B)
B = np.array([100, 120, 130])

# Solve for x, y, z
solution = np.linalg.solve(A, B)
print("Quantities of products A, B, and C:", solution)


Quantities of products A, B, and C: [22.77777778  9.44444444 26.11111111]
