# NumPy Array Indexing and Slicing

### 1D Array Indexing and Sliding

In [136]:
import numpy as np

In [138]:
a = np.arange(5)** 2
a

array([ 0,  1,  4,  9, 16])

In [140]:
a[3]

9

In [142]:
a[2:5]  # From 2 (included) to 5 (excluded)

array([ 4,  9, 16])

In [144]:
a


array([ 0,  1,  4,  9, 16])

In [146]:
a[:4:2]  # From 0 (included) to 4 (excluded) with a step 2

array([0, 4])

In [148]:
a[:4:2] = -100
a

array([-100,    1, -100,    9,   16])

In [150]:
a[::-1]  #Reverse (not done in place)

array([  16,    9, -100,    1, -100])

In [152]:
x=[1,2,3,4]
x[::-1]

[4, 3, 2, 1]

In [154]:
np.sort(a)[::-1]

array([  16,    9,    1, -100, -100])

### 2D Array Indexing

In [156]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [164]:
a[1,2] #[row,column]

5

In [33]:
a[1,2]

5

In [ ]:
a[1, 1]  #Preferred

In [ ]:
a[0,0]

### Compare with Indexing of a List of Lists

In [ ]:
b = [[0, 1, 2], [3, 4, 5]]
b

In [ ]:
b[1]

In [ ]:
b[1][1]

In [ ]:
b[1, 1] 

- `b[1, 1]` does not work.<br>

### 2D Array Slicing

In [166]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
a[1, 2:4]  # Red cells

array([7, 8])

In [49]:
a[3:, 3:]  # Green cells

array([[18, 19],
       [23, 24]])

<img src="images/2d_indexing.png" alt="2D Indexing" style="width: 150px;"/>

In [176]:
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [172]:
a[1,2:4]

array([7, 8])

In [170]:
# yellow
a[0:5:2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [168]:
# purple:
a[0:5,1]

array([ 1,  6, 11, 16, 21])

In [45]:

# yellow: row index: 0,2,4
# yellow: column index: 2,4
#a[0:5:2,2:5:2]
a[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [41]:
a[0:5, 1]  # Purple cells
a[:, 1]  # Purple cells

array([ 1,  6, 11, 16, 21])

In [ ]:
a[::2, 2::2]  # Yellow cells

### Fancy Indexing with Arrays of Integers

In [178]:
a = np.arange(5)**2  # Data array         
a

array([ 0,  1,  4,  9, 16])

In [180]:
i = np.array([3, 1, 3, 0])  # Index array
i

array([3, 1, 3, 0])

In [182]:
a[i]  # The shape is determined by the index array i
      # The elements come from the data array a.

array([9, 1, 9, 0])

In [ ]:
a[3]

In [184]:
a  # Data array

array([ 0,  1,  4,  9, 16])

In [186]:
j = np.array([[0,3], [2,1]])  #2D index array
j

array([[0, 3],
       [2, 1]])

In [188]:
a[j]  # The shape is determined by the index array
      # The elements come from the data array.

array([[0, 9],
       [4, 1]])

In [190]:
c = np.arange(12).reshape(3, 4)  # Data array
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
i = np.array([[0, 1], [1, 2]])  # Index array
i

array([[0, 1],
       [1, 2]])

In [194]:
j = np.array([[2, 1], [3, 3]])  # Index array
j

array([[2, 1],
       [3, 3]])

In [196]:
c[i, 2]


array([[ 2,  6],
       [ 6, 10]])

In [198]:
c[i, j]  # The index arrays for each dimension must have the same shape


array([[ 2,  5],
       [ 7, 11]])

In [200]:
c[i, j]=-1  # Use indexing to assign values
c

array([[ 0,  1, -1,  3],
       [ 4, -1,  6, -1],
       [ 8,  9, 10, -1]])

### Fancy Indexing with Boolean Arrays

In [202]:
a = np.arange(9).reshape(3, 3)  # Data array
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [204]:
b = a > 4  # Index array
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [77]:
a[b]

array([5, 6, 7, 8])

In [206]:
a[b] = -1  # Assign new values
a  # New data array

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [208]:
i = np.array([False, True, True])  # Index array
i

array([False,  True,  True])

In [210]:
j = np.array([True, False, True])  # Index array
j

array([ True, False,  True])

In [212]:
a

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [214]:
a[i, :]

array([[ 3,  4, -1],
       [-1, -1, -1]])

In [87]:
a[:, j]

array([[0, 2],
       [3, 5],
       [6, 8]])

### More About Fancy Indexing

In [216]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [218]:
a[(0, 2, 4), (0, 2, 4)]  # Red cells

array([ 0, 12, 24])

In [220]:
a[[1, 3, 4], 3:]  # Green cells

array([[ 8,  9],
       [18, 19],
       [23, 24]])

<img src="images/2d_fancy_indexing.png" alt="2D Fancy Indexing" style="width: 150px;"/>

In [95]:
mask = np.array([0, 1, 1, 1, 0], dtype=bool)
mask

array([False,  True,  True,  True, False])

In [97]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
a[1, mask]  # Purple cells

array([6, 7, 8])

In [101]:
imesh = np.ix_([1, 4], np.r_[0, 2:4])  # Index mesh
imesh

(array([[1],
        [4]]),
 array([[0, 2, 3]]))

In [103]:
a[imesh]  # Yellow cells

array([[ 5,  7,  8],
       [20, 22, 23]])

### Array Stacking

In [223]:
a = np.array([[0, 1], [2, 3]])
a

array([[0, 1],
       [2, 3]])

In [225]:
b = np.array([[0, -1], [-2, -3]])
b

array([[ 0, -1],
       [-2, -3]])

In [227]:
np.vstack([a, b])  # Lists or tuples
                   # np.vstack(a, b) does not work

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

In [229]:
np.hstack((a, b))  # Lists or tuples
                   # np.hstack(a, b) does not work

array([[ 0,  1,  0, -1],
       [ 2,  3, -2, -3]])

### Array Splitting

In [231]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [233]:
np.vsplit(a, 3)  # Split vertically (row-wise)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [235]:
np.hsplit(a, 3)  # Split horizontally (column-wise)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]