# NumPy Array Broadcasting

### The Basics

- Broadcasting is the way used by NumPy when dealing with arrays of different shapes during arithmetic operations.

In [41]:
import numpy as np

In [43]:
a = np.arange(3)
a

array([0, 1, 2])

In [45]:
b = 1
b

1

In [47]:
a + b

array([1, 2, 3])

<img src="images/broadcast1.png" alt="Broadcast 1" style="width: 300px;"/>

In [49]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [53]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])

<img src="images/broadcast2.png" alt="Broadcast 2" style="width: 300px;"/>

In [55]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
b = np.array([0, 1]).reshape(2, 1)
b

array([[0],
       [1]])

In [59]:
a + b

array([[0, 1, 2],
       [4, 5, 6]])

<img src="images/broadcast3.png" alt="Broadcast 3" style="width: 300px;"/>

In [61]:
b = 2
b

2

In [63]:
a + b

array([[2, 3, 4],
       [5, 6, 7]])

<img src="images/broadcast4.png" alt="Broadcast 4" style="width: 300px;"/>

In [66]:
a = np.array([0, 3]).reshape(2, 1)
a

array([[0],
       [3]])

In [68]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [70]:
a + b

array([[0, 1, 2],
       [3, 4, 5]])

<img src="images/broadcast5.png" alt="Broadcast 5" style="width: 300px;"/>

- If the dimensions mismatch, there will be an error.
<img src="images/broadcast_mismatch.png" alt="Broadcast Mismatch" style="width: 250px;"/>

### Example

- Calculate the distances between any two cities (Binghamton, Hancock, Middletown, Sloatsburg, NYC) on the route from Binghamton to NYC.
<img src="images/binghamton2nyc.png" alt="Binghamton to NYC" style="width: 250px;"/>

In [73]:
miles = np.array([0, 43, 120, 153, 190])  # Distances from Binghamton to each of these cities
miles

array([  0,  43, 120, 153, 190])

In [75]:
miles.reshape(5, 1)

array([[  0],
       [ 43],
       [120],
       [153],
       [190]])

In [79]:
miles - miles.reshape(5, 1)  # Distances between any two cities

array([[   0,   43,  120,  153,  190],
       [ -43,    0,   77,  110,  147],
       [-120,  -77,    0,   33,   70],
       [-153, -110,  -33,    0,   37],
       [-190, -147,  -70,  -37,    0]])

### In-Class Exercises

 Marketing Spend Distribution: You are given the total budget for a marketing campaign and the percentage allocations for 5 different channels (e.g., social media, TV, radio, etc.). Use broadcasting to calculate how much money should be allocated to each channel based on the percentage breakdown.

Total Budget: $1,000,000
Percentage Allocations:

- Social Media: 30%
- TV: 25%
- Radio: 20%
- Online Ads: 15%
- Print: 10%

In [81]:
# Solution
total_budget = 1000000
percentage_allocations = np.array([0.30, 0.25, 0.20, 0.15, 0.10])

# Broadcasting to calculate the distribution of the budget
channel_budgets = total_budget * percentage_allocations

print("\nMarketing spend distribution across channels:")
print(channel_budgets)


Marketing spend distribution across channels:
[300000. 250000. 200000. 150000. 100000.]


In [12]:

# Problem 2: Product Pricing Adjustment
price_data = np.array([
    [20, 25],  # Product 1
    [30, 35],  # Product 2
    [40, 45],  # Product 3
    [50, 55],  # Product 4
    [60, 65]   # Product 5
])

# Percentage adjustments: Domestic +5%, International -3%
adjustments = np.array([1.05, 0.97])
price_data = price_data*adjustments

print("\nAdjusted product prices for domestic and international markets:")
print(price_data)

# Problem 3: Marketing Spend Distribution
total_budget = 1_000_000
percentage_allocations = np.array([0.30, 0.25, 0.20, 0.15, 0.10])

# Broadcasting to calculate the distribution of the budget
channel_budgets = total_budget * percentage_allocations

print("\nMarketing spend distribution across channels:")
print(channel_budgets)



Adjusted product prices for domestic and international markets:
[[21.   24.25]
 [31.5  33.95]
 [42.   43.65]
 [52.5  53.35]
 [63.   63.05]]

Marketing spend distribution across channels:
[300000. 250000. 200000. 150000. 100000.]
